### ISSUE TITLE
Autocomplete from previously loaded scripts

### ISSUE THREAD

**Issue by scameron** [Sevin777/Ace.Tern#18]
I'm not sure if this is possible or not, but is there a way to get Tern to analyse a particular JS file that I'm pulling in so that when I reference the objects from that file in my Ace edited script the available properties, functions, etc show up?

For example, say I'm loading a utility or API JS like D3 or JQuery or something like that.  When I make use of that API in my Ace editor I only see autocomplete choices that are derived from what I've already done in my local JS (say if I have previously invoked function "a" I will see "a" show up as a suggestion).  Is there some way to get it to go a step further with the analysis/search?

**Comment by Sevin777** [comment]
Yes its designed to do this. See: https://github.com/sevin7676/Ace.Tern/blob/master/tabDemo.js#L199
and [Tern code](https://github.com/sevin7676/Ace.Tern/blob/master/ace-builds/src-noconflict/ext-tern.js#L396-413). 

This can also be done with automatically  RequireJS but it requires some extra config.

Also, for Jquery you can use the Tern definitions options:

https://github.com/sevin7676/Ace.Tern/blob/master/ace-builds/src-noconflict/ext-tern.js#L139

http://ternjs.net/doc/manual.html#typedef

You won't want to load a massive library and parse it on demand as it will be very slow, thats what the type definition files are for
