### ISSUE TITLE
Caret-T: Javascript autocomplete

### ISSUE THREAD

**Issue by postacik** [Sevin777/Ace.Tern#26]
Suppose I have file (a.js) with my functions in it.

In file b.js I write code which uses functions in a.js.

Can autocomplete give information about functions in a.js while working in b.js?

**Comment by Sevin777** [comment]
This is very similar to https://github.com/sevin7676/Ace.Tern/issues/18

This specific Tern extension has a quick hack to enable using the [Reference Path](http://blogs.msdn.com/b/webdev/archive/2007/11/06/jscript-intellisense-a-reference-for-the-reference-tag.aspx) tag supported by Visual Studio intellisense (also used by Type Script).

You can use this syntax as follows: _(must be at top of file, multiple lines allowed)_

```
/// <reference path="../a.js" />
/// <reference path="https://code.jquery.com/jquery-2.1.3.js" />
```

Also, the reference paths are not checked or updated until you call: `editor.ternServer.docChanged(editor)`

This method is a quick hack that is poorly implemented because I'm just using it for something specific. However, Tern supports adding other files for reference by configuring the [RequireJS plugin](http://ternjs.net/doc/manual.html#plugin_requirejs) or [Node plugin](http://ternjs.net/doc/manual.html#plugin_node). Example for rqeuireJS:

_[enableTern accepts boolean or configuration options](https://github.com/sevin7676/Ace.Tern/blob/518c52077756d927cfa5cc8b29c24be8b0da0784/ace-builds/src-noconflict/ext-tern.js#L190)_

```
 var editor = ace.edit("editor");
 ace.config.loadModule('ace/ext/language_tools', function() {
     ace.config.loadModule('ace/ext/tern', function() {
         editor.setOptions({
             enableTern: {
                 plugins: {
                     requirejs: {
                         baseURL: '(set this)',
                         paths: '(optional)',
                         override: '(optional)',
                     },
                     doc_comment: {
                         fullDocs: true
                     }
                 }
             },
             enableSnippets: false,
             enableBasicAutocompletion: true,
         });
     });
 });
```

**Comment by postacik** [comment]
I'm using your Caret-T Chrome application and when I put the reference line at the top of a file, it has no effect on autocomplete.

/// <reference path="../a.js" />

Is this feature possible in Caret-T?

(I posted the question in this project because Caret-T about box points to this project for getting the source code instead of CaretTern project)

**Comment by Sevin777** [comment]
Yes it works in Caret-T. After you add the file reference to the top of the file switch to another tab, then switch back and it will reload the references. 

Open Chrome's dev tools and look at the console as it logs info when it adds references including if it runs into an error:

![image](https://cloud.githubusercontent.com/assets/5360920/7026515/1e3bd5ea-dd18-11e4-9dfd-5c6b549e3c5b.png)

success:

![image](https://cloud.githubusercontent.com/assets/5360920/7026532/358a4038-dd18-11e4-8598-f37933aed69a.png)

**Comment by postacik** [comment]
I have the following lines in b.js

var goo =  {
    //stringProp
    stringProp: "",
    //mest property
    numProp: 10
};

goo.stringProp = "str";
goo.numProp = 20;

And a.js looks like this:

![image](https://cloud.githubusercontent.com/assets/3977227/7026789/8091bec6-dd54-11e4-8202-85658e8c628f.png)

When I type "goo." in a.js it does not display object goo's properties as they listed while working in b.js.

**Comment by Sevin777** [comment]
There is a bug that prevents local paths from working correctly unless they start with `../`, and they must not be at the root. So it will work if your file is `[root]/scripts/b.js` and you use `/// <reference path="../scripts/b.js" />`

I haven't got around to fixing this bug yet.

**Comment by postacik** [comment]
Thanks, it works when library and projects files are in seperate folders under the same root.

**Comment by postacik** [comment]
Can you update the project source code to include library files in demo.html file as you explain in your first answer to this issue?

**Comment by Sevin777** [comment]
I'm not sure what you referring to: `include library files in demo.html`

**Comment by postacik** [comment]
I mean adding external js files for autocomplete with the following code change:

![image](https://cloud.githubusercontent.com/assets/3977227/7028974/6a5c08c4-dd62-11e4-9f42-8eb1e7c41e41.png)

**Comment by postacik** [comment]
In ext-tern.js the following line exists in function loadExplicitVsRefs:

``` javascript
editor.ternServer.addDoc(path.replace(/^.*[\\\/]/, ''), xhr.responseText);
```

Can I add my js libraries to be used in autocomplete using this function?

**Comment by Sevin777** [comment]
Thats the code that automatically reads the `/// <reference path="" />` comments.

You can also use: `editor.ternServer.addDoc(fileName,fileContents)`  to manually add your source. https://github.com/sevin7676/Ace.Tern/blob/2d814fb4d2d68d0b4a765b6fcd07f96f8aaeb98f/ace-builds/src-noconflict/ext-tern.js#L425.

The demo has now been updated with better comments: https://github.com/sevin7676/Ace.Tern/blob/master/demo.html#L108

**Comment by postacik** [comment]
Thank you very much. The following instruction does what I need.

``` javascript
editor.ternServer.addDoc(fileName,fileContents)
```
