### ISSUE TITLE
Is it not possible to run demo.html locally?

### ISSUE THREAD

**Issue by postacik** [Sevin777/Ace.Tern#27]
I get the following error when I run demo.html locally.

Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///C:/Users/Desktop/Ace.Tern-master/ace-builds/src-noconflict/worker-tern.js' cannot be accessed from origin 'null'.

Is it not possible to run demo.html locally?

**Comment by Sevin777** [comment]
Correct. It uses a web worker which Chrome won't allow from a local file:

http://suretalent.blogspot.com/2011/04/javascript-web-workers-local-chrome.html

**Comment by angelozerr** [comment]
It should be very fantastic if we could avoid using worker and executing Ace.Tern in local.

I had done that https://github.com/angelozerr/tern.ace 

If Ace.Tern can be executed in local I will switch my tern.ace to Ace.tern in tern.java https://github.com/angelozerr/tern.java/wiki/Tern-Toolings

**Comment by postacik** [comment]
I'm sorry if the following is an ignorant question.

There are other worker files in ace (i.e. worker-javascript.js) which work fine locally.

Is worker-tern.js any different than that?

**Comment by Sevin777** [comment]
Ace can be set to not use a worker for javascript mode (which also disables a lot of functionality), but I have not set up Tern to not use a worker yet as it would require a good bit of refactoring and the performance is rather poor when not using a worker.

**Comment by postacik** [comment]
Thanks, I did understand what you mean when I read the following article about web workers.

http://ejohn.org/blog/web-workers/

**Comment by Sevin777** [comment]
It now works locally (supports not using web worker): https://github.com/sevin7676/Ace.Tern/blob/master/demo.html#L91

**Comment by postacik** [comment]
That's great. Thank you very much.

**Comment by angelozerr** [comment]
Very cool @sevin7676 I will try it and if it works in my case I will integrate it to tern.java.

Thanks!
