### ISSUE TITLE
Caret-T autocomplete vs. Ace.Tern

### ISSUE THREAD

**Issue by postacik** [Sevin777/Ace.Tern#28]
Caret-T autocomplete feature runs very well.

Can you compare Ace.Tern autocomplete to Caret-T?

Is the following project status stated in the demo application still valid or is the current version suitable for production environment?

"Under heavy development, not ready for prime time yet"
"This demo is not isolated, it has extra stuff that is not related to the demo that needs to be removed"

**Comment by Sevin777** [comment]
Ace.Tern auto complete code used by Caret-T.

I still consider the library to be under heavy development, and its code base is below the quality I would expect out of an official library.

The demo also contains my custom beautify extension, which is the not isolated part.
