### ISSUE TITLE
Bug in a blank document (Ace.Tern)

### ISSUE THREAD

**Issue by postacik** [Sevin777/Ace.Tern#29]
In a blank document when you start typing, the following hint appears:

![image](https://cloud.githubusercontent.com/assets/3977227/7062687/6efff5c4-dea8-11e4-9242-48b84569d490.png)

Can this be fixed?

**Comment by Sevin777** [comment]
Fixed https://github.com/sevin7676/Ace.Tern/commit/3f0e77b278ec89433d25aed7a42f4b5190dfecbf

**Comment by postacik** [comment]
Thanks...
