### ISSUE TITLE
caret-T not available on chrome webstore

### ISSUE THREAD

**Issue by aonghusonia** [Sevin777/Ace.Tern#42]
I just got a new chromebook and was dismayed to see my favorite editor was missing from the chrome webstore, I hope it it temporary or else I will have to figure out how install it from github.

Keep up the good work
Aonghus

**Comment by aonghusonia** [comment]
just showed up thanks

**Comment by Sevin777** [comment]
Something was going on with Google because I didn't make any changes. I checked last night and it was indeed missing, and now its back.
