### ISSUE TITLE
undo/redo operation only working for first tab!!

### ISSUE THREAD

**Issue by Ravinderjitsidhu** [Sevin777/Ace.Tern#43]
undo/redo operation only working for first tab... this must be fixed to fulfill the purpose of making tabs

**Comment by Ravinderjitsidhu** [comment]
I got solution.
I have found that only first tab was having "undo/redo"  working and other tabs were not.
then i found that one node is missing in other tabs :
**"editor.ternServer.docs.tab2.doc.$undoManager"**
then i got the idea to add undoManager in all  the tabs.....and other thing that we can save undoManager stack data in array and can restore on selecting other tab.

_to add UndoManager to tab_ :
**editor.getSession().setUndoManager(new ace.UndoManager());**

_to put undo stack data of current tab in array :_ 
**undoStacks[currTabNumber] = editor.getSession().$undoManager**;   

_to restore UndoManager stack data to current tab :_
**editor.getSession().$undoManager=undoStacks[currTabNumber]**;

thanks

**Comment by Sevin777** [comment]
Is this bug for Caret-T?

**Comment by Ravinderjitsidhu** [comment]
it will produce when you run tabdemo.html

**Comment by Sevin777** [comment]
tabdemo.html is not complete (not even close) and I have no plans for finishing it
