### ISSUE TITLE
How should this be integrated with ACE.

### ISSUE THREAD

**Issue by anandanand84** [Sevin777/Ace.Tern#44]
Is it possible to integrate this plugin using existing ACE by just adding an ext-tern from this library. Or we should use the ace editor completely from this repository?

**Comment by Sevin777** [comment]
The ace editor from this repository is the same as the ace editor from the ace repository (but likely outdated)

**Comment by anandanand84** [comment]
Can you add a package.json and publish it to the npm repository in that case? How frequent do you merge this with ACE?

**Comment by Sevin777** [comment]
Read the 'building' section in the [readme ](https://github.com/sevin7676/Ace.Tern/blob/master/README.md), from there you can find the last time I updated from ACE. I am not adding package.json for many reasons, the first of which is I don't have time to work on this.
