### ISSUE TITLE
Update to work with latest version of Ace

### ISSUE THREAD

**Issue by rbiggs** [Sevin777/Ace.Tern#47]
I noticed that this only works with Ace version 1.1.9. The latest version of Ace is 1.2.5. That has lots of bug fixes. Unfortunately you can't just replace Ace and its ext, modes, etc. The tern webworker seems to break with that. Any idea how to get this working with a newer version of Ace?

**Comment by Sevin777** [comment]
I will have to look at whats breaking it, but that is likely not going to happen for a while because I'm very busy with other projects. 

Feel free to fix it and submit a pull request, see https://github.com/sevin7676/Ace.Tern#building

**Comment by rbiggs** [comment]
Something to do with the 1.2.5 handling of deltas. They changed how deltas are handled with a new object structure that I think the worker doesn't understand or expect. I get an error about `docLines[endRow].substring(endColumn)` in all browsers.

**Comment by Sevin777** [comment]
This now works with Ace 1.2.6
