### ISSUE TITLE
Working together?

### ISSUE THREAD

**Issue by angelozerr** [Sevin777/Ace.Tern#6]
@sevin7676 I had created a tern support for ACE https://github.com/angelozerr/tern.ace. Perhaps we could collaborae to avoid having several projects?

**Comment by Sevin777** [comment]
I started with a fork of your project but found that the direction you were going in was very different from the direction that I wanted to go in so I started fresh. The tern plugin I've made is very similar to the tern plugin for CodeMirror. The one you made is very different: it shows tooltips and inserts 'snippets' for function calls.

**Comment by Sevin777** [comment]
If you want to see this plugin in action try Caret-T from the Chrome Web Store: https://chrome.google.com/webstore/detail/caret-t/agiednhnlghobdgpgfdnbdaflnngmoij

**Comment by angelozerr** [comment]
I have tested your demo https://github.com/sevin7676/Ace.Tern/blob/master/tabDemo.html which works with FF, but not with Chrome. A very cool demo.

IMHO, I think it's shame that we have 2 projects which have the same goal. I think we should merg eour project.

Today I use my tern.ace inside Eclipse https://github.com/angelozerr/tern.java/wiki/Tern-Toolings#tern-web-browser-wizard but perhaps I could use your own if we merge our work.

**Comment by angelozerr** [comment]
> The one you made is very different: it shows tooltips and inserts 'snippets' for function calls.

I think we could provide some option to enable/disable that.

**Comment by Sevin777** [comment]
The demo works fine in Chrome (Chrome is the only browser I use). You are likely trying to run the demo from a file in Chrome, which is not allowed (you need to use a local web server) due to Chrome's security policy.

Automatic tooltips on hover in Tern causes serious performance issues when you start using larger files and the parameters as snippets is less useful than argument hints (my opinion). However I wouldn't have a problem allowing these features as options if you wanted to post a pull request.

Added [live demo](http://sevin7676.github.io/Ace.Tern/demo.html)

**Comment by angelozerr** [comment]
@sevin7676 I have no time to support tern.ace, so I would like to use your tern ace in the eclipse wizard of tern.java https://github.com/angelozerr/tern.java/wiki/Tern-Toolings#tern-web-browser-editor-wizards

> you need to use a local web server

I think it's a big problem. In my case it works without web server. The eclipse wizard generate ace, CM or orion editor in a html page with selected plugins. After you can open the generated html page and play directly (without web server). To debug your tern plugin, it's very helpfull.

So if you have the intention  to use your tern ace without web server, I will replace my tern ace by yours inside tern.java

**Comment by Sevin777** [comment]
This is likely because I have Tern set up to run in a worker, which I don't think is supported for local files. I will update the code at some point to make Tern use a worker based on Ace's `Use Worker` setting.
